import { Metadata } from 'next';
import type { AppProps } from 'next/app';

export const metadata: Metadata = {
    title: "My App",
    description: "Generated by create next app",
  };
export default function App({ Component, pageProps }: AppProps) {
    return <Component {...pageProps} />
}